### ISSUE TITLE
[Suggestion] Use `multisession.el` or `persist.el`

### ISSUE THREAD

**Issue by josephmturner** [charmitro/emacs-ssh-machines#1]
Nice package idea!  Instead of using `prin1`  to persist `ssh-machines-list`, I recommend using `multisession.el` (built into Emacs 29) or `persist.el` (available on GNU ELPA).

Here's an example usage of `multisession.el` from the [Emacs info manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Multisession-Variables.html):

```
     (define-multisession-variable foo-var 0)
     (defun my-adder (num)
       (interactive "nAdd number: ")
       (setf (multisession-value foo)
             (+ (multisession-value foo) num))
       (message "The new number is: %s" (multisession-value foo)))
```

**Comment by charmitro** [comment]
Hi @josephmturner! Thank you very much for this.

Multisession variables look great! I definitely want to use them instead of saving data to a predefined file of my own. Do you know if multisession is compatible with lists?

**Comment by josephmturner** [comment]
@charmitro Nice!

**Comment by charmitro** [comment]
> @charmitro Nice!

Way better now, thanks for the suggestion!
